Gtmp 16
XsourceTech/backend_dev pull request #6
Opened 2024-08-19 20:23 UTC by qiuziyuan

implement Authentication Service

2024-08-19 20:31 UTC, ChrisMa2024 reviewed
let's also add in tests in the same PR, this should be applied to all future code, i will do the same for my futture PR as well

2024-08-19 20:31 UTC, ChrisMa2024 commented on auth_service/app/logging_config.py
> +    logger.setLevel(logging.DEBUG)
For consistency purposes, let's use centralized logging, we can use the logger from database_sharing_service, since we already use same database, no need for logging configuration per service

2024-08-19 20:39 UTC, ChrisMa2024 commented
BTW, let's also add auth_client in the user_service so that it can be used later

2024-08-19 22:56 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +        return response.json()
I think we just need access_token here?

2024-08-20 00:33 UTC, qiuziyuan commented on user_service/clients/auth_client.py
> +        return response.json()
Fixed.

2024-08-20 03:04 UTC, ChrisMa2024 commented
test 都跑过了吧？ @qiuziyuan

2024-08-20 03:05 UTC, ChrisMa2024 approved these changes
Assume tests are passing, ship!

2024-08-20 04:05 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +    def generate_token(self, email: str, password: str):
Let's actually update the naming here, since we merged in the functionality of authenticating user into generate token function, let's just call it authenticate_user

2024-08-20 04:16 UTC, ChrisMa2024 requested changes

2024-08-20 04:16 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +        response.raise_for_status()
We shouldn't be raising exceptions if we don't set up a way to handle them, we can either just returning for 200, and return nothing for other status or set up some exception handling logic here in the code.

2024-08-20 04:16 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +        response.raise_for_status()
same here, we want to wrap these into a try/except clause, and log these exceptions according to there category

2024-08-20 10:29 UTC, qiuziyuan commented
> test 都跑过了吧？ @qiuziyuan

跑过了

2024-08-20 11:06 UTC, qiuziyuan commented on user_service/clients/auth_client.py
> +    def generate_token(self, email: str, password: str):
In auth_service.app.main, is it necessary to correct the naming in the same way?

2024-08-20 11:13 UTC, qiuziyuan commented on user_service/clients/auth_client.py
> +        response.raise_for_status()
Because in the logging_config, logger = logging.getLogger("database_sharing_service"), the log records will all display 'database_sharing_service'. Will this be an issue?

2024-08-20 11:15 UTC, qiuziyuan commented on user_service/clients/auth_client.py
> +        response.raise_for_status()
> same here, we want to wrap these into a try/except clause, and log these exceptions according to there category

Done.

2024-08-21 06:12 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +    def generate_token(self, email: str, password: str):
Not necessary since the main function is still generating token, maybe we should consider separating the logic for authenticating user as a separate function, but we r pretty tight on time, we can consider this as optional and file a jira ticket as tech debt to be done in a later time

2024-08-21 06:24 UTC, ChrisMa2024 commented on user_service/clients/auth_client.py
> +        response.raise_for_status()
i updated logging config file in my branch, i will push mine first so that you can just initialize the logger in your service to show different service names

2024-08-21 19:02 UTC, merged